# Generated by Django 2.2.1 on 2019-08-17 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymdb', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
