# Generated by Django 2.2.1 on 2019-08-24 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Movie')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Category')),
            ],
            options={
                'unique_together': {('name', 'movie')},
            },
        ),
    ]
