# Generated by Django 2.2.1 on 2019-08-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_categoryrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='categorized', through='core.CategoryRelation', to='core.Category'),
        ),
    ]
