# Generated by Django 2.2.1 on 2019-08-24 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_movie_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryrelation',
            old_name='name',
            new_name='category',
        ),
        migrations.AlterUniqueTogether(
            name='categoryrelation',
            unique_together={('category', 'movie')},
        ),
    ]
